# Day 5 – NumPy Basics and Array Operations

## Objective
Understand NumPy arrays and perform basic numerical and aggregation operations used in data analysis.

## Import NumPy

In [1]:
import numpy as np

## Creating NumPy Arrays

In [2]:
# 1D Array
arr_1d = np.array([10, 20, 30, 40, 50])
print(arr_1d)

# 2D Array
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr_2d)

[10 20 30 40 50]
[[1 2 3]
 [4 5 6]]


## Array Properties

In [8]:
print("Shape:", arr_2d.shape)
print("Size:", arr_2d.size)
print("Dimensions:", arr_2d.ndim)
print("Data Type:", arr_2d.dtype)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int64


## Indexing & Slicing

In [9]:
# Indexing
print(arr_1d[2])
print(arr_2d[1, 1])

# Slicing
print(arr_1d[1:4])
print(arr_2d[:, 1])

30
5
[20 30 40]
[2 5]


## Array Operations

In [10]:
a = np.array([10, 20, 30])
b = np.array([2, 2, 2])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 22 32]
Multiplication: [20 40 60]
Division: [ 5. 10. 15.]


## Aggregation Functions

In [11]:
numbers = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(numbers))
print("Mean:", np.mean(numbers))
print("Max:", np.max(numbers))
print("Min:", np.min(numbers))

Sum: 150
Mean: 30.0
Max: 50
Min: 10


## Key Takeaways
- NumPy arrays are faster and more memory-efficient than Python lists
- Vectorized operations simplify numerical computations
- NumPy forms the foundation for Pandas and data analysis workflows